- name: QCD
  types:
    - QCD
  title: QCD
  color: kBlue-10 #kOrange-3
- name: DY
  types:
    - DY
  title: "DY #rightarrow ll + jets"
  color: kCyan-6 #kAzure+10
- name: TT
  types:
    - TT
  title: t#bar{t}
  color: kSpring+5 #kGreen+3
- name: ST
  types:
    - ST
  title: "ST"
  color: kYellow-9 #kTeal-9
- name: VV
  types:
    - VV
  title: "VV"
  color: kOrange-4 #kPink+1
- name: single_H
  title: "H"
  types:
    - ttH
    - VH
    - H
  color: kRed-10 #kRed-7
- name: Other
  title: "Other"
  types: []
  color: kPink+2 #kViolet+4
- name: GluGluToBulkGraviton_1250
  title: "GGBG-1250"
  type: signal
  types:
   - GluGluToBulkGraviton
  color: kCyan
  #scale: 0.05
- name: GluGluToRadion_1250
  title: "GGR-1250"
  type: signal
  types:
   - GluGluToRadion
  color: kRed
- name: GluGluToRadion_700
  title: "GGR-700"
  type: signal
  types:
   - GluGluToRadion
  color: kYellow
- name: GluGluToRadion_450
  title: "GGR-450"
  type: signal
  types:
   - GluGluToRadion
  color: kGreen
- name: data
  title: "data obs"
  types:
    - data
  type: data
#- name: W
  #types:
  #  - W
  #title: "W #rightarrow l#nu + jets"
  #color: kYellow-7