############## WJetsToLNu ##############
WtoLNu_amcatnloFXFX:
  sampleType: W


############## TT ##############
TT:
  sampleType: TT
TTTo2L2Nu:
  sampleType: TT
TTTo4Q:
  sampleType: TT
TTToLNu2Q:
  sampleType: TT


############## DY ##############
DYto2L_M_10to50_amcatnloFXFX:
  sampleType: DY
DYto2L_M_50_amcatnloFXFX:
  sampleType: DY

############## VV inclusive ##############
WW:
  sampleType: VV
WZ:
  sampleType: VV
ZZ:
  sampleType: VV


############## VVV inclusive ##############
WWW_4F:
  sampleType: VVV
WWZ_4F:
  sampleType: VVV
WZZ:
  sampleType: VVV
ZZZ:
  sampleType: VVV

############## ST #############
ST_t_channel_antitop_4f_InclusiveDecays:
  sampleType: ST
ST_t_channel_top_4f_InclusiveDecays:
  sampleType: ST
ST_tW_antitop_2L2Nu:
  sampleType: ST
ST_tW_antitop_4Q:
  sampleType: ST
ST_tW_antitop_LNu2Q:
  sampleType: ST
ST_tW_top_2L2Nu:
  sampleType: ST
ST_tW_top_4Q:
  sampleType: ST
ST_tW_top_LNu2Q:
  sampleType: ST

############## TTX inclusive ##############
TTWW:
  sampleType: TTVV
TTWH:
  sampleType: TTVV
TTZH:
  sampleType: TTVV
TTZZ:
  sampleType: TTVV

############## ttH ##############
ttHToNonbb_M125:
 sampleType: ttH
ttHTobb_M125:
  sampleType: ttH

# # https://github.com/valeriadamante/NanoProd
# ############## WJetsToLNu ##############
# WJetsToLNu:
#   sampleType: W

# W1JetsToLNu:
#   sampleType: W
# W2JetsToLNu:
#   sampleType: W
# W3JetsToLNu:
#   sampleType: W
# W4JetsToLNu:
#   sampleType: W

# WJetsToLNu_HT-100To200:
#   sampleType: W
# WJetsToLNu_HT-1200To2500:
#   sampleType: W
# WJetsToLNu_HT-200To400:
#   sampleType: W
# WJetsToLNu_HT-2500ToInf:
#   sampleType: W
# WJetsToLNu_HT-400To600:
#   sampleType: W
# WJetsToLNu_HT-600To800:
#   sampleType: W
# WJetsToLNu_HT-70To100:
#   sampleType: W
# WJetsToLNu_HT-800To1200:
#   sampleType: W


# ############## TT ##############
# TTTo2L2Nu:
#   sampleType: TT
# TTToHadronic:
#   sampleType: TT
# TTToSemiLeptonic:
#   sampleType: TT


# ############## DY ##############
# DYJetsToLL_M-50-amcatnloFXFX:
#   sampleType: DY
# DYJetsToLL_0J-amcatnloFXFX:
#  sampleType: DY
# DYJetsToLL_1J-amcatnloFXFX:
#  sampleType: DY
# DYJetsToLL_2J-amcatnloFXFX:
#  sampleType: DY
# DYJetsToLL_LHEFilterPtZ-0To50-amcatnloFXFX:
#  sampleType: DY
# DYJetsToLL_LHEFilterPtZ-50To100-amcatnloFXFX:
#  sampleType: DY
# DYJetsToLL_LHEFilterPtZ-100To250-amcatnloFXFX:
#  sampleType: DY
# DYJetsToLL_LHEFilterPtZ-250To400-amcatnloFXFX:
#  sampleType: DY
# DYJetsToLL_LHEFilterPtZ-400To650-amcatnloFXFX:
#  sampleType: DY
# DYJetsToLL_LHEFilterPtZ-650ToInf-amcatnloFXFX:
#  sampleType: DY

# ############## EWK ##############
# EWK_ZTo2L:
#   sampleType: EWK
# EWK_ZTo2Nu:
#   sampleType: EWK
# EWK_WplusToLNu:
#   sampleType: EWK
# EWK_WminusToLNu:
#   sampleType: EWK

# ############## single Higgs ##############
# ggHToZZTo2L2Q:
#   sampleType: H
# GluGluHToTauTau_M125:
#   sampleType: H
# VBFHToTauTau_M125:
#   sampleType: H
# GluGluHToWWTo2L2Nu_M125:
#   sampleType: H
# VBFHToWWTo2L2Nu_M125:
#   sampleType: H

# ############## VH non-inclusive ##############
# WplusHToTauTau_M125:
#   sampleType: VH
# WminusHToTauTau_M125:
#   sampleType: VH
# ZHToTauTau_M125:
#   sampleType: VH
# ZH_Hbb_Zll:
#   sampleType: VH
# ZH_Hbb_Zqq:
#   sampleType: VH
# HWplusJ_HToWW_M125:
#   sampleType: VH
# HWminusJ_HToWW_M125:
#   sampleType: VH
# HZJ_HToWW_M125:
#   sampleType: VH

# ############## VV inclusive ##############
# WW:
#   sampleType: VV
# WZ:
#   sampleType: VV
# ZZ:
#   sampleType: VV


# ############## VVV inclusive ##############
# WWW_4F:
#   sampleType: VVV
# WWZ_4F:
#   sampleType: VVV
# WZZ:
#   sampleType: VVV
# ZZZ:
#   sampleType: VVV

# ############## ST #############
# ST_t-channel_antitop_4f_InclusiveDecays:
#   sampleType: ST
# ST_t-channel_top_4f_InclusiveDecays:
#   sampleType: ST
# ST_tW_antitop_5f_InclusiveDecays:
#   sampleType: ST
# ST_tW_top_5f_InclusiveDecays:
#   sampleType: ST


# ############## TTX inclusive ##############
# TTWW:
#   sampleType: TTX
# TTWH:
#   sampleType: TTX
# TTZH:
#   sampleType: TTX
# TTZZ:
#   sampleType: TTX
# TTWZ:
#   sampleType: TTX
# TTTT:
#   sampleType: TTX
# TTTW:
#   sampleType: TTX
# TTTJ:
#   sampleType: TTX
# TTGG:
#   sampleType: TTX
# TTGJets:
#   sampleType: TTX
# TT4b:
#   sampleType: TTX

# ############## ttH ##############
# #ttHToNonbb_M125:
# #  sampleType: ttH
# ttHTobb_M125:
#   sampleType: ttH
# ttHToTauTau_M125:
#   sampleType: ttH

