anaTupleDef: AnaProd/HH_bbtautau/anaTupleDef.py
signal_types: []
  #- GluGluToRadion
  #- GluGluToBulkGraviton
  #- VBFToRadion
  #- VBFToBulkGraviton
genuineTau_SFtype:
  eTau: dm
  muTau: dm
  tauTau: dm
deepTauWPs:
  eTau:
    VSe: VVLoose
    VSmu: Tight
    VSjet: Medium
  muTau:
    VSe: VVLoose
    VSmu: Tight
    VSjet: Medium
  tauTau:
    VSe: VVLoose
    VSmu: Tight
    VSjet: Medium
corrections:
  # - tauID
  # - tauES
  # - JEC
  # - JER
  # - trg
  # - btagWP
  # - btagShape
  # - mu
  # - ele
  # - puJetID
  - pu
deepTauVersion: 2p1
channelSelection:
  - eTau
  - muTau
  - eE
  - eMu
  - muMu
  - tauTau
QCDRegions:
  - OS_Iso
  # - SS_Iso
  # - OS_AntiIso
  # - SS_AntiIso
categories:
  - res1b
  - res2b
  - inclusive
  - boosted
  - btag_shape
  - baseline
storeExtraJets: False
deepTauYears:
  v2p1: 2017
  v2p5: 2018



channels_to_consider:
  - tauTau
  - eTau
  - muTau
  - eE
  - eMu
  - muMu
  - tauTau
gen_channels:
  eTau:
    - 3
    - 5
  muTau:
    - 4
    - 5
  tauTau:
    - 5
    - 5

channelDefinition:
  eTau: 13
  muTau: 23
  tauTau: 33
  eE: 11
  eMu: 12
  muMu: 22


triggers:
  eTau:  HLT_singleEle || HLT_etau || HLT_singleTau || HLT_MET
  muTau: HLT_singleMu || HLT_mutau || HLT_singleTau || HLT_MET
  tauTau: HLT_ditau || HLT_singleTau || HLT_MET
  eE: HLT_singleEle || HLT_MET
  eMu: HLT_singleEle || HLT_singleMu || HLT_MET
  muMu: HLT_singleMu || HLT_MET

hist_triggers:
  eTau:  ((HLT_singleEle && SingleEle_region) || (HLT_singleTau && SingleTau_region) || (HLT_MET && MET_region ))
  #eTau:  (((HLT_singleEle || HLT_etau ) && (SingleEle_region || CrossEleTau_region) )|| (HLT_singleTau && SingleTau_region)  || (HLT_MET && MET_region ))
  muTau: ((HLT_singleMu && SingleMu_region) || (HLT_singleTau && SingleTau_region) || (HLT_MET && MET_region ))
  #muTau: (((HLT_singleMu || HLT_mutau ) && (SingleMu_region || CrossMuTau_region) ) || (HLT_singleTau && SingleTau_region)  || (HLT_MET && MET_region ))
  tauTau: ((HLT_ditau && Legacy_region) || (HLT_singleTau && SingleTau_region && !Legacy_region)  || (HLT_MET && MET_region ) )
  eE: (HLT_singleEle && SingleEle_region)
  eMu: ((HLT_singleEle && SingleEle_region) || (HLT_singleMu && SingleMu_region))
  muMu: (HLT_singleMu && SingleMu_region)

application_regions:
  HLT_singleMu:
    region_name: SingleMu_region
    region_cut: ((tau1_pt > 26 && abs(tau1_eta) < 2.4) ||  (tau2_pt > 26 && abs(tau2_eta) < 2.4))
  HLT_mutau:
    region_name: CrossMuTau_region
    region_cut: (tau1_pt > 22 && abs(tau1_eta) < 2.1 && tau2_pt > 32 && abs(tau2_eta) < 2.1)
  HLT_singleEle:
    region_name: SingleEle_region
    region_cut: ((tau1_pt > 33 && abs(tau1_eta) < 2.5) || (tau2_pt > 33 && abs(tau2_eta) < 2.5))
  HLT_etau:
    region_name: CrossEleTau_region
    region_cut: (tau1_pt > 25 && abs(tau1_eta) < 2.1 && tau2_pt > 35 && abs(tau2_eta) < 2.1)
  HLT_ditau:
    region_name: Legacy_region
    region_cut: (tau1_pt > 40 && tau2_pt > 40)
  HLT_singleTau:
    region_name: SingleTau_region
    region_cut: (((tau1_pt >= {tau_th} && abs(tau1_eta) < 2.1) || (tau2_pt >= {tau_th} && abs(tau2_eta) < 2.1)) )
  HLT_MET:
    region_name: MET_region
    region_cut: (!(Legacy_region) && !(SingleTau_region))

# singleMu_th:
#   "Run2_2016": 26
#   "Run2_2016_HIPM": 26
#   "Run2_2017": 29
#   "Run2_2018": 26
#   "Run3_2022":

# singleEle_th:
#   "Run2_2016": 26
#   "Run2_2016_HIPM": 26
#   "Run2_2017": 33
#   "Run2_2018": 33
#   "Run3_2022":

singleTau_th:
  "Run2_2016": 130
  "Run2_2016_HIPM": 130
  "Run2_2017": 190
  "Run2_2018": 190
#   "Run3_2022":

# eTau_th:
#   "Run2_2016":
#   "Run2_2016_HIPM":
#   "Run2_2017":
#   "Run2_2018":
#   "Run3_2022":

# muTau_th:
#   "Run2_2016":
#   "Run2_2016_HIPM":
#   "Run2_2017":
#   "Run2_2018":
#   "Run3_2022":

btag_wps:
  res2b: Medium
  res1b: Medium
  boosted: Loose

mass_cut_limits:
  bb_m_vis:
    - 40
    - 270
  tautau_m_vis:
    - 20
    - 130

scales:
  - Up
  - Down


# preVFP == APV == HIPM
unc_2018:
  - JES_BBEC1_2018
  - JES_Absolute_2018
  - JES_EC2_2018
  - JES_HF_2018
  - JES_RelativeSample_2018
unc_2017:
  -JES_BBEC1_2017
  - JES_Absolute_2017
  - JES_EC2_2017
  - JES_HF_2017
  - JES_RelativeSample_2017
unc_2016preVFP:
  -JES_BBEC1_2016preVFP
  - JES_Absolute_2016preVFP
  - JES_EC2_2016preVFP
  - JES_HF_2016preVFP
  - JES_RelativeSample_2016preVFP
unc_2016postVFP:
  -JES_BBEC1_2016postVFP
  - JES_Absolute_2016postVFP
  - JES_EC2_2016postVFP
  - JES_HF_2016postVFP
  - JES_RelativeSample_2016postVFP

sample_types_to_merge:
  - DY
  - TT
  - W
  - ST
  - VV

uncs_to_exclude :
  Run3_2022: []
  Run3_2022EE: []
  Run2_2018:
    - JES_BBEC1_2017
    - JES_Absolute_2017
    - JES_EC2_2017
    - JES_HF_2017
    - JES_RelativeSample_2017
    - JES_BBEC1_2016preVFP
    - JES_Absolute_2016preVFP
    - JES_EC2_2016preVFP
    - JES_HF_2016preVFP
    - JES_RelativeSample_2016preVFP
    - JES_BBEC1_2016postVFP
    - JES_Absolute_2016postVFP
    - JES_EC2_2016postVFP
    - JES_HF_2016postVFP
    - JES_RelativeSample_2016postVFP
  Run2_2017:
    - JES_BBEC1_2018
    - JES_Absolute_2018
    - JES_EC2_2018
    - JES_HF_2018
    - JES_RelativeSample_2018
    - JES_BBEC1_2016preVFP
    - JES_Absolute_2016preVFP
    - JES_EC2_2016preVFP
    - JES_HF_2016preVFP
    - JES_RelativeSample_2016preVFP
    - JES_BBEC1_2016postVFP
    - JES_Absolute_2016postVFP
    - JES_EC2_2016postVFP
    - JES_HF_2016postVFP
    - JES_RelativeSample_2016postVFP
  Run2_2016:
    - JES_BBEC1_2018
    - JES_Absolute_2018
    - JES_EC2_2018
    - JES_HF_2018
    - JES_RelativeSample_2018
    - JES_BBEC1_2017
    - JES_Absolute_2017
    - JES_EC2_2017
    - JES_HF_2017
    - JES_RelativeSample_2017
    - JES_BBEC1_2016preVFP
    - JES_Absolute_2016preVFP
    - JES_EC2_2016preVFP
    - JES_HF_2016preVFP
    - JES_RelativeSample_2016preVFP
  Run2_2016_HIPM:
    - JES_BBEC1_2018
    - JES_Absolute_2018
    - JES_EC2_2018
    - JES_HF_2018
    - JES_RelativeSample_2018
    - JES_BBEC1_2017
    - JES_Absolute_2017
    - JES_EC2_2017
    - JES_HF_2017
    - JES_RelativeSample_2017
    - JES_BBEC1_2016postVFP
    - JES_Absolute_2016postVFP
    - JES_EC2_2016postVFP
    - JES_HF_2016postVFP
    - JES_RelativeSample_2016postVFP
bjet_vars:
  - b1_pt
  - b2_pt
  - b1_eta
  - b2_eta

FatJetObservables :
  - area
  - btagCSVV2
  - btagDDBvLV2
  - btagDeepB
  - btagHbb
  - deepTagMD_HbbvsQCD
  - deepTagMD_ZHbbvsQCD
  - deepTagMD_ZbbvsQCD
  - deepTagMD_bbvsLight
  - deepTag_H
  - jetId
  - msoftdrop
  - nBHadrons
  - nCHadrons
  - nConstituents
  - rawFactor
  - particleNetMD_QCD
  - particleNetMD_Xbb
  - particleNet_HbbvsQCD
  - particleNet_mass
  - particleNet_QCD
  - particleNet_XbbVsQCD
  - particleNetLegacy_QCD
  - particleNetLegacy_Xbb
  - particleNetLegacy_mass
  - particleNetWithMass_QCD
  - particleNetWithMass_HbbvsQCD
  - particleNet_massCorr
  - p4
  - pt
  - eta
  - phi
  - mass


unc_to_not_consider_boosted:
  - PUJetID
  - JER
  - JES_FlavorQCD
  - JES_RelativeBal
  - JES_HF
  - JES_BBEC1
  - JES_EC2
  - JES_Absolute
  - JES_Total
  - JES_BBEC1_2018
  - JES_Absolute_2018
  - JES_EC2_2018
  - JES_HF_2018
  - JES_RelativeSample_2018
  - bTagSF_Loose_btagSFbc_correlated
  - bTagSF_Loose_btagSFbc_uncorrelated
  - bTagSF_Loose_btagSFlight_correlated
  - bTagSF_Loose_btagSFlight_uncorrelated
  - bTagSF_Medium_btagSFbc_correlated
  - bTagSF_Medium_btagSFbc_uncorrelated
  - bTagSF_Medium_btagSFlight_correlated
  - bTagSF_Medium_btagSFlight_uncorrelated
  - bTagSF_Tight_btagSFbc_correlated
  - bTagSF_Tight_btagSFbc_uncorrelated
  - bTagSF_Tight_btagSFlight_correlated
  - bTagSF_Tight_btagSFlight_uncorrelated
  - bTagShapeSF_lf
  - bTagShapeSF_hf
  - bTagShapeSF_lfstats1
  - bTagShapeSF_lfstats2
  - bTagShapeSF_hfstats1
  - bTagShapeSF_hfstats2
  - bTagShapeSF_cferr1
  - bTagShapeSF_cferr2
