ditau:
  channels:
    - tauTau
  path_data:
    - HLT_DoubleMediumDeepTauPFTauHPS35_L2NN_eta2p1
  legs:
    - offline_obj:
        type: Tau
        cut: v_ops::pt(Tau_p4) > 40 && abs(v_ops::eta(Tau_p4)) < 2.1
      online_obj:
        cuts:
          - cut: TrigObj_id==15 && (TrigObj_filterBits&2)!=0 && (TrigObj_filterBits&256)!=0
      doMatching: True
    #- ref_leg: 0

singleMu:
  channels:
    - muTau
    - muMu
    - eMu
  path:
    - HLT_IsoMu24
    - HLT_IsoMu24_eta2p1
  legs:
    - offline_obj:
        type: Muon
        cut:  v_ops::pt(Muon_p4) > 24 && abs(v_ops::eta(Muon_p4)) < 2.1
      online_obj:
        cut: TrigObj_id == 13 && (TrigObj_filterBits&32)!=0
      doMatching: True

mutau:
  channels:
    - muTau
  path:
    - HLT_IsoMu24_eta2p1_LooseDeepTauPFTauHPS180_eta2p1
    - HLT_IsoMu20_eta2p1_LooseDeepTauPFTauHPS27_eta2p1_CrossL1
  legs:
    - offline_obj:
        type: Muon
        cut: v_ops::pt(Muon_p4) > 21 && abs(v_ops::eta(Muon_p4)) < 2.1
      online_obj:
        cut: TrigObj_id==13 && (TrigObj_filterBits&32)!=0 && TrigObj_pt>19
      doMatching: True
    - offline_obj:
        type: Tau
        cut: v_ops::pt(Tau_p4) > 25 && abs(v_ops::eta(Tau_p4)) < 2.1
      online_obj:
        cut: TrigObj_id==15 && (TrigObj_filterBits&32)!=0  && (TrigObj_filterBits&1)!=0
      doMatching: True

MET:
    channels:
      - tauTau
      - muTau
      - eTau
    path:
      - HLT_PFMETNoMu120_PFMHTNoMu120_IDTight
    legs:
      - offline_obj:
          type: MET
          cut: metnomu_pt > 150
        doMatching: False

singleEle:
  channels:
    - eTau
    - eE
    - eMu
  path:
    - HLT_Ele27_WPTight_Gsf
  legs:
    - offline_obj:
        type: Electron
        cut: v_ops::pt(Electron_p4) > 27 && abs(v_ops::eta(Electron_p4)) < 2.5
      online_obj:
        cut: TrigObj_id == 11 && (TrigObj_filterBits&2)!=0
      doMatching: True

etau:
  channels:
    - eTau
  path_data:
    - HLT_Ele24_eta2p1_WPTight_Gsf_LooseDeepTauPFTauHPS30_eta2p1_CrossL1
  legs:
    - offline_obj:
        type: Electron
        cut: v_ops::pt(Electron_p4) > 26 && abs(v_ops::eta(Electron_p4)) < 2.1
      online_obj:
        cut: TrigObj_id==11 && (TrigObj_filterBits&8)!=0 && TrigObj_pt>24
      doMatching: True
    - offline_obj:
        type: Tau
        cut: v_ops::pt(Tau_p4) > 25 && abs(v_ops::eta(Tau_p4)) < 2.1
      online_obj:
        cut:  TrigObj_id==15 && (TrigObj_filterBits&64)!=0 && (TrigObj_filterBits&1)!=0
      doMatching: True